
<h2 class="Title">Ajouter un candidat</h2>
<form action="index.php?action=addCandidate" method="post" class="AddCandidate" >
    <div class="AddCandidate-lastName AddCandidateForm">
        <label class="AddCandidateForm-lastName" for="lastName">Nom : </label>
        <input class="AddCandidateForm-content" type="text" name="lastName">
        <?php if(isset($errors['lastName'])):?>
            <p class="AddCandidateForm-error" > <?= $errors['lastName'] ?> </p>
        <?php  endif?>
    </div>
    
    <div class="AddCandidate-firstName AddCandidateForm">
        <label for="firstName">Prénom : </label>
        <input class="AddCandidateForm-content" type="text" name="firstName">
        <?php if(isset($errors['firstName'])):?>
            <p class="AddCandidateForm-error" > <?= $errors['firstName'] ?> </p>
            <?php  endif?>
    </div>
    <div class="AddCandidate-email AddCandidateForm">
        <label for="email">Email : </label>
        <input class="AddCandidateForm-content" type="text" name="email">
        <?php if(isset($errors['email'])):?>
            <p class="AddCandidateForm-error"> <?= $errors['email'] ?> </p>
        <?php  endif?>
    </div>
    <div class="AddCandidate-phone AddCandidateForm">
        <label for="phone">Numéro de téléphone : </label>
        <input class="AddCandidateForm-content" type="text" name="phone">
        <?php if(isset($errors['phone'])):?>
            <p class="AddCandidateForm-error"> <?= $errors['phone'] ?> </p>
            <?php  endif?>
    </div>
    <div class="Addcandidate-pe AddCandidateForm">
        <label for="pe">Identifiant pole emploi : </label>
        <input class="AddCandidateForm-content" type="text" name="pe" maxlength="20">
    </div>
    <div class="AddCandidateForm">
        <input class="AddCandidateForm-button" type="submit" value="Envoyer">
    </div>
</form>