<!-- TODO ajouter un filtre de recherche -->
<h2 class="Title">Rechercher une réunion</h2>
    <form class=" SearchForm" action="#">    
        <div class="SearchForm-name">
            <label class="AllCandidate-form" for="">Nom de la réunion : </label>
            <input type="text">
        </div>
        <div class="SearchForm-formation">
            <label class="AllCandidate-form" for="">Formation concernée : </label>
            <input type="text">
        </div>
        
        <input class="SearchForm-button" type="submit" value="rechercher">
        
    </form>
<!-- On boucle pour afficher toute les réunions -->
<section class="Meetings">
    <?php foreach($meetings as $meeting): ?>
        <article class="Meetings-content">
            <h2 class="Meetings-content-title"> <?= $meeting['name'] ?> </h2>
            <p> <?= $meeting['meetingDate'] ?> </p>
            <a href="index.php?action=meeting&id_event=<?=$meeting['id_event']?>"><img class="Meetings-content-img" src="../public/img/<?=$meeting['image']?>" alt="image pour la réunion infoco"></a>
        </article>
        <?php endforeach ?>
</section>