<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Réunion d'information relative aux formations du GRETA CFA">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet"> 
    <script src="https://unpkg.com/phosphor-icons"></script>
    <link rel="stylesheet" href="../public/css/style.css">
    <title>GretaInfoCo</title>
</head>
<body>
    <?php if($this->userSession->isConnected()): ?>
        <header class="Header">
            <button class="button-burger" id="btn-menu" type="button"></button>
            <nav class='Header-nav'>     
                <a class="Header-nav-link" href="index.php?action=allMeeting">Les réunions</a>
                <a class="Header-nav-link"  href="index.php?action=candidates">Les candidats</a>
            </nav>

            <h1 class="Header-title"> <a href="index.php">Greta InfoCo</a></h1>


                <div class="Header-admin">
                    <div class="Header-plus-menu">
                        <a class="Header-nav-link AdminLink" href="index.php?action=addCandidate">ajouter un candidat</a>
                        <a class="Header-nav-link AdminLink"  href="index.php?action=createMeeting">ajouter une réunion</a>
                    </div>
                    <button id="HeaderPlus" class="Header-plus"> <i class="ph-plus-thin"></i> </button>
                    <a href="index.php?action=logout">Se déconnecter</a>
                </div>
            </header>
    <?php endif ?>

    <main>
        <?php include TEMPLATE_DIR . '/' . $template . '.phtml';?>     
           
    <script src="../public/js/index.js"></script>
    </main>
</body>
</html>