<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Réunion d'information relative aux formations du GRETA CFA">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet"> 
    <script src="https://unpkg.com/phosphor-icons"></script>
    <link rel="stylesheet" href="../public/css/style.css">
    <script defer src="../public/js/index.js"></script>
    <title>GretaInfoCo</title>
</head>
<body>
  
    <?php if($this->userSession->isConnected()): ?>
        <header class="Header">
            <button class="button-burger" id="btn-menu" type="button"></button>
            <nav class='Header-nav'>     
                <a class="Header-nav-link" href="index.php?action=allMeeting">Les réunions</a>
                <a class="Header-nav-link HeaderHideDesktop"  href="index.php?action=createMeeting">ajouter une réunion</a>
                <a class="Header-nav-link"  href="index.php?action=candidates">Les candidats</a>
                <a class="Header-nav-link HeaderHideDesktop" href="index.php?action=addCandidate">ajouter un candidat</a>
            </nav>
        

            <h1 class="Header-title"> <a href="index.php">Greta InfoCo</a></h1>


                <div class="Header-admin">
                    <div class="Header-button-menu">
                        <a class="Header-nav-link HeaderHideMobile" href="index.php?action=addCandidate">ajouter un candidat</a>
                        <a class="Header-nav-link HeaderHideMobile"  href="index.php?action=createMeeting">ajouter une réunion</a>
                    </div>
                    <button id="HeaderPlus" class="Header-button"> <i class="ph-plus-thin"></i> </button>
                    <a class="Header-admin-deconnect" href="index.php?action=logout">Déconnexion</a>
                </div>
            </header>
            <?php endif ?>
            
            <main class="Main">
                <?php include TEMPLATE_DIR . '/' . $template . '.phtml';?> 
            </main>

    <?php if($this->userSession->isConnected()): ?>
        <footer class="Footer">
            <p>mention légale</p>
            <p>Contact</p>
        </footer>   
    <?php endif ?> 
    
        
</body>
</html>