
    <h2 class="Title">Rechercher un candidat</h2>
    <form class="AllCandidate-form SearchForm" action="#">    
        <div class="SearchForm-name">
            <label class="AllCandidate-form" for="">Nom : </label>
            <input type="text">
        </div>
        <div class="SearchForm-formation">
            <label class="AllCandidate-form" for="">Formation concernée : </label>
            <input type="text">
        </div>
        
        <input class="SearchForm-button" type="submit" value="rechercher">
        
    </form>
<section class="Candidates">
    <?php foreach($candidates as $candidate): ?> 
        <article class="AllCandidate">

            <div class="AllCandidate-info">
                <a class="AllCandidate-info-link" href="index.php?action=candidate&id_candidat=<?=$candidate['id_candidat']?>"><h2 class="AllCandidate-info-name"><?= $candidate['nom'] . ' ' . $candidate['prenom']  ?> </h2></a>
                <p class="AllCandidate-info-email"> <?=$candidate['email'] ?> </p>
                <p class="AllCandidate-info-number"> <?=$candidate['telephone'] ?> </p>
            </div>
            <div class="AllCandidate-contact">
                <a href="index.php?action=candidate&id_candidat=<?=$candidate['id_candidat']?>">Contacter</a>
            </div>
        </article>  
    <?php endforeach ?>
        
</section>