
<p>Créer une nouvelle réunion d'information : </p>


<form action="index.php?action=createMeeting" method="POST">
    <fieldset>
        <label for="name">Donnez un nom à votre réunion : </label>
        <input type="text" id="name" name="name">
        <label for="formation">Titre de formation concerné : </label>
        <select name="formation" id="formation">
            <!-- todo : boucle sur les différents titres insérés dans notre BDD -->
            <?php foreach($formations as $formation): ?>
                <option value="<?= $formation['id_formation'] ?> "><?= $formation['titreFormation'] ?> </option>
            <?php endforeach ?>
         
            </option>
        </select>

        <label for="place">lieu de la réunion : </label>
        <select name="place" id="place">
            <!-- boucle sur les différents lieux insérés dans notreBDD -->
            <?php foreach($places as $place): ?>
                <option value="<?= $place['id_lieu'] ?> "><?= $place['lieu'] ?> </option>
            <?php endforeach ?>

        </select>
        <label for="meetingTime">Date de la réunion : </label>
        <input type="datetime-local" id="meetingTime" name="meetingTime">

        <button type="submit">Créer la réunion</button>
    </fieldset>

</form>