<?php var_dump($candidates) ?>
<p>page d'une réunion</p>
<h2><?= $meeting['name'] ?></h2>
<h3>Réunion du : <?= $meeting['meetingDate'] ?></h3>
<table>
    <thead>
        <tr>
            <th colspan="2"><?= $meeting['name'] ?></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td> Date de la réunion :  <?= $meeting['meetingDate'] ?></td>
        </tr>
        <tr>
            <td>Titre de la formation concernée : <?= htmlspecialchars($meeting['titreFormation']) ?></td>
        </tr>

        <?php foreach($candidates as $candidat): ?>
            <tr>
                <td>Prénom :  <?= htmlspecialchars($candidat['prenom']) ?> </td>
                <td>nom :  <?= htmlspecialchars($candidat['nom']) ?> </td>
                <td>Email :  <?= htmlspecialchars($candidat['email']) ?> </td>
                <td>Commentaires :  <?= htmlspecialchars($candidat['commentairesReunion']) ?> </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>

