
<h2 class="Title">Éditer un candidat</h2>
<form action="index.php?action=editCandidate&id_candidat=<?=$candidate['id_candidat']?>" method="POST" class="Adding">
<div class="WrapperNameInfo">
    <div class="WrapperFormName">

        <div class="Adding-lastName AddingForm">
            <label class="AddingForm-lastName" for="lastName">Nom : </label>
            <input class="AddingForm-content" id="lastName" type="text" name="lastName" value="<?=$candidate['nom']?>">
            <?php if(isset($errors['lastName'])):?>
                <p class="AddingForm-error"> <?= $errors['lastName'] ?> </p>
            <?php  endif?>
        </div>
            
        <div class="Adding-firstName AddingForm">
            <label for="firstName">Prénom : </label>
            <input class="AddingForm-content" type="text" name="firstName" value="<?=$candidate['prenom']?>">
            <?php if(isset($errors['firstName'])):?>
                <p class="AddingForm-error" > <?= $errors['firstName'] ?> </p>
                <?php  endif?>
        </div>

        <div class="Adding-email AddingForm">
            <label for="email">Email : </label>
            <input class="AddingForm-content" type="text" name="email" value="<?=$candidate['email']?>">
            <?php if(isset($errors['email'])):?>
                <p class="AddingForm-error"> <?= $errors['email'] ?> </p>
            <?php  endif?>
        </div>
    </div>

    <div class="WrapperFormInfo">
        <div class="Adding-phone AddingForm">
            <label for="phone">Numéro de téléphone : </label>
            <input class="AddingForm-content" type="text" name="phone" value="<?=$candidate['telephone']?>">
            <?php if(isset($errors['phone'])):?>
                <p class="AddingForm-error"> <?= $errors['phone'] ?> </p>
                <?php  endif?>
        </div>
        <div class="Adding-adress AddingForm">
            <label for="adress">Adresse : </label>
            <input class="AddingForm-content" type="text" id="adress" name="adress" value="<?=$candidate['adresse']?>">
        </div>
        <div class="Adding-bac AddingForm">
            <label for="participate">Bac (oui/non) : </label>
            <input class="AddingForm-content" type="text" name="bac" maxlength="20" value="<?=$candidate['bac']?>">
        </div>
    </div>
</div>

<div class="WrapperPeReunion">
    <div class="WrapperPe">
        <div class="Adding-pe AddingForm">
            <label for="pe">Identifiant pole emploi : </label>
            <input class="AddingForm-content" type="text" name="pe" maxlength="20" value="<?=$candidate['id_poleEmploi']?>">
        </div>
        <div class="Adding-peAdvisor AddingForm">
            <label for="peAdvisor">Conseiller pole emploi : </label>
            <input class="AddingForm-content" type="text" name="peAdvisor" maxlength="20" value="<?=$candidate['conseillerPE']?>">
        </div>
    </div>
    
    <div class="WrapperCodeReunion">
        <div class="Adding-codeRegion AddingForm">
            <label for="peAdvisor">Code région : </label>
            <input class="AddingForm-content" type="text" name="regionCode" maxlength="20" value="<?=$candidate['codeRegion']?>">
        </div>
        <div class="Adding-participate AddingForm">
            <label for="participate">Le candidat a participé à la réunion  : </label>
            <input class="AddingForm-content" type="text" name="participate" maxlength="20" value="<?=$candidate['participation']?>">
        </div>
    </div>
</div>

    
    <div class="Adding-comments AddingForm">
        <label for="comments">commentaires : </label>
        <textarea class="AddingForm-content" type="text" id="comments" name="comments"></textarea>
    </div>
    <div class="AddingForm">
        <input class="AddingForm-button" type="submit" value="Éditer">
    </div>
</form>